import type { IconType } from "react-icons";
import {
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiJavascript,
  SiHtml5,
  SiNodedotjs,
  SiDjango,
  SiFlask,
  SiPython,
  SiGnubash,
  SiOpenstack,
  SiDocker,
  SiKubernetes,
  SiRedhatopenshift,
  SiVmware,
  SiHelm,
  SiJenkins,
  SiGitlab,
  SiGit,
  SiAnsible,
  SiTerraform,
  SiLinux,
  SiApple,
} from "react-icons/si";
import { FaAws, FaMicrosoft, FaWindows } from "react-icons/fa";

export const skillIcons: Record<string, IconType> = {
  "React.js": SiReact,
  "Next.js": SiNextdotjs,
  TypeScript: SiTypescript,
  "TypeScript/JavaScript": SiTypescript,
  JavaScript: SiJavascript,
  "HTML/CSS": SiHtml5,
  "Node.js": SiNodedotjs,
  Django: SiDjango,
  Flask: SiFlask,
  Python: SiPython,
  Bash: SiGnubash,
  Shell: SiGnubash,
  AWS: FaAws,
  Azure: FaMicrosoft,
  OpenStack: SiOpenstack,
  Docker: SiDocker,
  Kubernetes: SiKubernetes,
  OpenShift: SiRedhatopenshift,
  "VMware PKS": SiVmware,
  "AWS EKS": FaAws,
  Helm: SiHelm,
  Jenkins: SiJenkins,
  "GitLab CI": SiGitlab,
  "Azure DevOps": FaMicrosoft,
  "AWS Developer Tools": FaAws,
  Git: SiGit,
  Ansible: SiAnsible,
  Terraform: SiTerraform,
  "AWS CloudFormation": FaAws,
  "Azure ARM": FaMicrosoft,
  Linux: SiLinux,
  "Unix (macOS)": SiApple,
  Windows: FaWindows,
};
